### PR TITLE
Re-worked TreeMap comparators, considering null-keys

### LINKED ISSUE #1549: TreeMap.get throws NPE when the key is present and any value is null
TreeMap.get will throw a null pointer exception when trying to do a lookup on a map with nulls in the values. HashMap works as expected under the same circumstances.

``` java
void bug() {
    final HashMap<String, String> hashMap = HashMap.of(
            "Thisworks", "fine",
            "evenwith", null);

    hashMap.get("nokey");     // Option.none()
    hashMap.get("Thisworks"); // Option.some("fine")
    hashMap.get("evenwith");  // Option.some(null)

    final TreeMap<String, String> treeMap = TreeMap.of(
            "thisbreaks", "themap",
            "lolhax", null);

    treeMap.get("nokey");       // Option.none()
    treeMap.get("thisbreaks"); // NPE
    treeMap.get("lolhax");     // NPE
}
```

I'm using javaslang 2.0.3

Stack trace:

```
java.lang.NullPointerException
    at javaslang.Tuple2.compareTo(Tuple2.java:80)
    at javaslang.Tuple2.compareTo(Tuple2.java:96)
    at javaslang.Tuple2.compareTo(Tuple2.java:28)
    at javaslang.collection.RedBlackTreeModule$Node.find(RedBlackTree.java:418)
    at javaslang.collection.TreeMap.get(TreeMap.java:420)

```

### PR DESCRIPTION
**Pull request by danieldietrich**
Fixes #1549 

```java
Map<K, V> map = TreeMap.empty();

// ordinary Maps are expected to accept null values:
map.put(null, "ok");
```

### CODE REVIEW

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 1]
```diff
@@ -448,7 +448,7 @@ private TreeMap(RedBlackTree<Tuple2<K, V>> entries) {
      * @return A new Map containing the given entries
      */
     public static <K, V> TreeMap<K, V> of(Comparator<? super K> keyComparator, K k1, V v1, K k2, V v2, K k3, V v3, K k4, V v4) {
-        return of(keyComparator, k1, v1, k2, v2, k3, v3).put(k4, v4);
```
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: The previous version called TreeMap.put, which was bad for these reasons:

* TreeMap.put was called, which creates RedBlackTree-wrappers
* of(...) recursively called O(n) times of() before starting to add values

The current version

* calls put on RedBlackTree, which does not create intermediate TreeMap objects
* turns the recursive call into an iteration, which is more efficient in this case

File: javaslang/src/test/java/javaslang/collection/TreeMapTest.java [hunk 2]
```diff
@@ -37,7 +37,7 @@ protected String className() {
 
     @Override
     protected <T1 extends Comparable<? super T1>, T2> TreeMap<T1, T2> emptyMap() {
-        return TreeMap.empty(nullsFirst());
```
Comment (danieldietrich) [inline javaslang/src/test/java/javaslang/collection/TreeMapTest.java]: Using nullsFirst() was terribly wrong. It made unit tests artificially work which were not intended to work.

File: javaslang/src/test/java/javaslang/collection/AbstractMapTest.java [hunk 3]
```diff
@@ -1056,6 +1057,54 @@ public void shouldReplaceAllValuesWithFunctionResult() {
...
+
+        System.out.println(treeMap.get("nokey"));       // Option.none()
+        System.out.println(treeMap.get("thisbreaks")); // NPE
+        System.out.println(treeMap.get("lolhax"));     // NPE
+
+        final TreeMap<Integer, ?> treeMap2 = TreeMap.of(
+                1, null, 2, null, 3, null);
+        treeMap2.get(2);
+
+    }
```
Comment (danieldietrich) [inline javaslang/src/test/java/javaslang/collection/AbstractMapTest.java]: will remove this in a second...

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 4]
```diff
@@ -1177,25 +1154,6 @@ public int size() {
...
-     * @return A new TreeMap.
-     */
-    @SuppressWarnings("unchecked")
-    private static <K, V> TreeMap<K, V> createTreeMap(Comparator<? super Tuple2<K, V>> comparator,
-                                                      Iterable<? extends Tuple2<? extends K, ? extends V>> entries) {
-        RedBlackTree<Tuple2<K, V>> tree = RedBlackTree.empty(comparator);
-        for (Tuple2<? extends K, ? extends V> entry : entries) {
-            tree = tree.insert((Tuple2<K, V>) entry);
-        }
-        return tree.isEmpty() ? (TreeMap<K, V>) empty() : new TreeMap<>(tree);
```
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: this was wrong, because the comparator was not used in the empty case

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 5]
```diff
@@ -140,26 +147,20 @@ private TreeMap(RedBlackTree<Tuple2<K, V>> entries) {
...
+     * @param map A map entry.
+     * @param <K> The key type
+     * @param <V> The value type
+     * @return A new Map containing the given map
      */
-    public static <K, V> TreeMap<K, V> of(Comparator<? super K> keyComparator, Tuple2<? extends K, ? extends V> entry) {
-        Objects.requireNonNull(keyComparator, "keyComparator is null");
-        Objects.requireNonNull(entry, "entry is null");
-        return TreeMap.<K, V> empty(keyComparator).put(entry);
+    public static <K, V> TreeMap<K, V> ofAll(Comparator<? super K> keyComparator, java.util.Map<? extends K, ? extends V> map) {
```
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: this method was missing

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 6]
```diff
@@ -775,22 +765,20 @@ private TreeMap(RedBlackTree<Tuple2<K, V>> entries) {
...
+    // -- TreeMap API
+
     @Override
     public <K2, V2> TreeMap<K2, V2> bimap(Function<? super K, ? extends K2> keyMapper, Function<? super V, ? extends V2> valueMapper) {
-        return bimap(naturalComparator(), keyMapper, valueMapper);
+        return bimap(this, EntryComparator.natural(), keyMapper, valueMapper);
+    }
+
+    @Override
+    public <K2, V2> TreeMap<K2, V2> bimap(Comparator<? super K2> keyComparator,
```
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 7]
```diff
@@ -1225,34 +1183,201 @@ public String toString() {
         return mkString(stringPrefix() + "(", ", ", ")");
     }
 
+    // -- private helpers
+
+    private static <K, K2, V, V2> TreeMap<K2, V2> bimap(TreeMap<K, V> map, EntryComparator<K2, V2> entryComparator,
```
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 8]
```diff
@@ -1225,34 +1183,201 @@ public String toString() {
...
+            Function<? super K, ? extends K2> keyMapper, Function<? super V, ? extends V2> valueMapper) {
+        Objects.requireNonNull(keyMapper, "keyMapper is null");
+        Objects.requireNonNull(valueMapper, "valueMapper is null");
+        return createTreeMap(entryComparator, map.entries, entry -> entry.map(keyMapper, valueMapper));
+    }
+
+    private static <K, V, K2, V2> TreeMap<K2, V2> flatMap(TreeMap<K, V> map, EntryComparator<K2, V2> entryComparator,
```
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 9]
```diff
@@ -1225,34 +1183,201 @@ public String toString() {
...
+            BiFunction<? super K, ? super V, ? extends Iterable<Tuple2<K2, V2>>> mapper) {
+        Objects.requireNonNull(mapper, "mapper is null");
+        return createTreeMap(entryComparator, map.entries.iterator().flatMap(entry -> mapper.apply(entry._1, entry._2)));
+    }
+
+    private static <K, K2, V, V2> TreeMap<K2, V2> map(TreeMap<K, V> map, EntryComparator<K2, V2> entryComparator,
```
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 10]
```diff
@@ -1225,34 +1183,201 @@ public String toString() {
...
+            Iterable<? extends Tuple2<? extends K, ? extends V>> entries) {
+        Objects.requireNonNull(entries, "entries is null");
+        RedBlackTree<Tuple2<K, V>> tree = RedBlackTree.empty(entryComparator);
+        for (Tuple2<K, V> entry : (Iterable<Tuple2<K, V>>) entries) {
+            tree = tree.insert(entry);
+        }
+        return new TreeMap<>(tree);
+    }
+
+    private static <K, K2, V, V2> TreeMap<K2, V2> createTreeMap(EntryComparator<K2, V2> entryComparator,
```
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java [hunk 11]
```diff
@@ -1225,34 +1183,201 @@ public String toString() {
...
-            return keyComparator.compare(e1._1, e2._1);
+        Comparator<K> keyComparator();
+
+        // -- internal impls
+
+        final class Specific<K, V> implements EntryComparator<K, V> {
+
+            private static final long serialVersionUID = 1L;
+
+            final Comparator<K> keyComparator;
```
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Variable 'keyComparator' must be private and have accessor methods\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 6 above)
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 7 above)
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 8 above)
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 9 above)
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 10 above)
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: no, it must not

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 11 above)
Comment (danieldietrich) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: private: ok
accessor methods: oh my god - no!

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 6 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 7 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 9 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 10 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 6 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 7 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 8 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

File: javaslang/src/main/java/javaslang/collection/TreeMap.java (hunk 9 above)
Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'K2' must match pattern '^\[A\-Z\]$'\.

Comment (sputnikci) [inline javaslang/src/main/java/javaslang/collection/TreeMap.java]: \[Checkstyle\] ERROR: Name 'V2' must match pattern '^\[A\-Z\]$'\.

**Comment by danieldietrich** [comment]
This was the last fix for 2.0.5 - now starting to cherry-pick.
