### PR TITLE
Implement HashMap.map, fix HashSet.equals

### LINKED ISSUE #503: NPE thrown while combining Stream.groupBy with Map.map
While working on one of Euler problems I've found a nasty bug,
for now I've isolated it in a test and I'm working on a fix for it,
please see below for the details.

The following (not yet existing in master) test is failing:

```java
@Test
public void shouldGroupByAndMapProperly() {
   assertThat(Stream.of(1)
      .groupBy(Function.identity())
      .map(entry -> entry.key)
      .toList()).isEqualTo(List.of(1));
}
```
```
java.lang.NullPointerException
	at javaslang.collection.StreamTest.shouldGroupByAndMapProperly(StreamTest.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
whereas, the corresponding scala code produces the expected results, without any problems:

```scala
Stream(1)
  .groupBy(e => e)
  .map(entry => entry._1)
  .toList
```

```
List[Int] = List(1)
```

### PR DESCRIPTION
**Pull request by patrox**
As a "side effect" of running tests for `HashMap.map`,
a problem with `HashSet.equals` was identified and fixed.

Fixes #503 and #504.

### CODE REVIEW

File: src/main/java/javaslang/collection/HashMap.java [hunk 1]
```diff
@@ -258,10 +258,10 @@ public int length() {
     public <U, W> Map<U, W> map(BiFunction<? super K, ? super V, ? extends Entry<? extends U, ? extends W>> mapper) {
         return null;
     }
-
     @Override
     public <U> Set<U> map(Function<? super Entry<K, V>, ? extends U> mapper) {
-        return null;
+        Objects.requireNonNull(mapper, "mapper is null");
+        return foldLeft(HashSet.empty(), (acc, entry) -> acc.add(mapper.apply(entry)));
```
Comment (danieldietrich) [inline src/main/java/javaslang/collection/HashMap.java]: this is nice!

Comment (patrox) [inline src/main/java/javaslang/collection/HashMap.java]: I took the functional route to do it. I think that mr. Odersky would be satisfied ;)

File: src/main/java/javaslang/collection/HashSet.java [hunk 2]
```diff
@@ -481,11 +481,12 @@ public int hashCode() {
     }
 
     @Override
+    @SuppressWarnings("unchecked")
     public boolean equals(Object o) {
         if (o == this) {
             return true;
         } else if (o instanceof HashSet) {
-            final HashSet<?> that = (HashSet<?>) o;
+            final HashSet<T> that = (HashSet<T>) o;
```
Comment (danieldietrich) [inline src/main/java/javaslang/collection/HashSet.java]: I tested a little bit and recognized that we need another equals implementation.

The underlying HashArrayMappedTrie may have stored the elements in an arbitrary order, so that the iterators do not return the elements in a specific order.

This lead to this implementation:

```java
@SuppressWarnings("unchecked")
@Override
public boolean equals(Object o) {
    if (o == this) {
        return true;
    } else if (o instanceof HashSet) {
        final HashSet<?> that = (HashSet<?>) o;
        return this.length() == that.length() && ((HashSet<Object>) this).containsAll(that);
    } else {
        return false;
    }
}
```

We do not cast to `<T>` in order to prevent ClassCastExceptions.

Thanks for for your finding!!

File: src/main/java/javaslang/collection/HashMap.java (hunk 1 above)
Comment (danieldietrich) [inline src/main/java/javaslang/collection/HashMap.java]: :+1:

**Comment by patrox** [comment]
OK, so I will close this one, as `HashMap.map` will be implemented in a separate PR.
Bottom line is that implementing Euler project problems (using javaslang) is a very good way to test it very thoroughly - it's a bit like an integration test - as we're mixing various types (Streams, Maps, Sets, CharSeqs) with various methods.

**Comment by danieldietrich** [comment]
Yes, the Euler tests are great for testing Javaslang.

Please implement the equals method in this PR I suggested above. I will pull it then. HashMap needs no separate PR.

Thx!

**Comment by danieldietrich** [comment]
I will take care now of flatMap and map in general as described here: https://github.com/javaslang/javaslang/issues/488#issuecomment-133760856

I can pull this into master today...

**Comment by patrox** [comment]
Done, coverage increased by 0.2% :)
But I'm still wondering how the order of elements in `HashArrayMappedTrie` could affect the `HashSet`s from my 'minimal' example - containing 1 element ?

**Comment by danieldietrich** [comment]
Many thanks :)

For your minimal example all should be ok. Currently it is not clear why the Iterator.equals failed - we will further investigate. The order of similar elements may change in general (having more than one element) because the Map (or HAMT) has a key set with no guarantee of order.
