### PR TITLE
Serializable

### LINKED ISSUE #1810: Make interfaces Serializable
@ggalmazor noted that we (unintentionally) changed the object serializability. E.g. Option isn't serializable any more (but Some and None are). This hinders us from adding fields of interface types (like Option) to serializable classes.

There are exceptions, stateful types should **not** implement Serializable:

* Future
* Promise
* Iterator

Also API specific types should not implement it:

* For
* Match, Case, Pattern
* ...

### PR DESCRIPTION
**Pull request by danieldietrich**
Fixes #1810

### CODE REVIEW

File: javaslang/src/test/java/javaslang/AbstractValueTest.java [hunk 1]
```diff
@@ -981,14 +981,14 @@ private boolean isSerializable() {
                         instanceOf(Either.LeftProjection.class),
                         instanceOf(Either.RightProjection.class),
                         instanceOf(Future.class),
-                        instanceOf(Iterator.class),
-                        instanceOf(Validation.class)
+                        instanceOf(Iterator.class)
```
Comment (danieldietrich) [inline javaslang/src/test/java/javaslang/AbstractValueTest.java]: Matches before `instanceOf(Traversable.class)` is checked, so it is ok.

File: javaslang/src/test/java/javaslang/AbstractValueTest.java [hunk 2]
```diff
@@ -981,14 +981,14 @@ private boolean isSerializable() {
...
                 ), false),
                 Case(anyOf(
                         instanceOf(Either.class),
                         instanceOf(Option.class),
                         instanceOf(Try.class),
-                        instanceOf(Traversable.class)
+                        instanceOf(Traversable.class),
```
Comment (danieldietrich) [inline javaslang/src/test/java/javaslang/AbstractValueTest.java]: In 3.0.0 Iterator will not implement Traversable any more (i.e. all internal `ofAll(iterator)` calls will be substituted with `ofAll(() -> iterator)`). So all Traversables will be Serializable.
